# Generated by Django 6.0.6 on 2026-06-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(max_length=50, verbose_name='联系电话')),
                ('company_brand', models.CharField(blank=True, max_length=150, verbose_name='公司/品牌')),
                ('project_type', models.CharField(blank=True, max_length=100, verbose_name='项目类型')),
                ('expected_quantity', models.CharField(blank=True, max_length=100, verbose_name='预计数量')),
                ('delivery_city', models.CharField(blank=True, max_length=100, verbose_name='交付城市')),
                ('budget_range', models.CharField(blank=True, max_length=100, verbose_name='预算区间')),
                ('requirement_description', models.TextField(blank=True, verbose_name='需求说明')),
            ],
            options={
                'verbose_name': '联系表单',
                'verbose_name_plural': '联系表单',
                'db_table': 'contract',
            },
        ),
    ]
